version: "3.9"

services:

  geth:
    build: ./geth-node
    ports:
      - "8545:8545"
    volumes:
      - ./geth-node/data:/geth/data

  backend:
    build:
      context: .
      dockerfile: ./sibive-backend/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - CONTRACT_INFO_PATH=/app/runtime/contract_info.json
      - LOG_DIR=/app/runtime
    volumes:
      - ./sibive-backend/runtime:/app/runtime
    depends_on:
      - geth
    restart: unless-stopped

  frontend:
    build: ./sibive-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
